// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"gochicoba/handler"
	"gochicoba/repository"
	"gochicoba/service"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func BuyHandler(db *gorm.DB) handler.BuyHandler {
	buyRepository := repository.NewBuyRepository(db)
	buyService := service.NewBuyService(buyRepository)
	buyHandler := handler.NewBuyHandler(buyService)
	return buyHandler
}
